name: Android Build and Release

on:
  push:
    tags:
      - 'v*'  # 当推送 v 开头的标签时触发（如 v1.0.0）
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FileTransferAndroid  # 指定你的Android项目目录

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17  # Android需要JDK17+
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    # 还原签名密钥
    - name: Restore Keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > release.keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    # 设置签名环境变量
    - name: Setup signing variables
      run: |
        echo "RELEASE_STORE_FILE=release.keystore" >> $GITHUB_ENV
        echo "RELEASE_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> $GITHUB_ENV
        echo "RELEASE_KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
        echo "RELEASE_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease
      env:
        ORG_GRADLE_PROJECT_RELEASE_STORE_FILE: ${{ env.RELEASE_STORE_FILE }}
        ORG_GRADLE_PROJECT_RELEASE_STORE_PASSWORD: ${{ env.RELEASE_STORE_PASSWORD }}
        ORG_GRADLE_PROJECT_RELEASE_KEY_ALIAS: ${{ env.RELEASE_KEY_ALIAS }}
        ORG_GRADLE_PROJECT_RELEASE_KEY_PASSWORD: ${{ env.RELEASE_KEY_PASSWORD }}

    # 上传APK到Release
    - name: Upload APK to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')  # 仅在标签推送时执行
      with:
        files: app/build/outputs/apk/release/*.apk
        generate_release_notes: true
